# Sesión live: entra directamente al escritorio XFCE con el usuario gmini.
[Seat:*]
greeter-session=lightdm-gtk-greeter
user-session=xfce
autologin-user=gmini
autologin-user-timeout=0
autologin-session=xfce
