# Initramfs de la ISO: los hooks de archiso montan la imagen squashfs. Sin los
# hooks de arranque por red (PXE) de releng.
HOOKS=(base udev microcode modconf kms memdisk archiso archiso_loop_mnt block filesystems keyboard)
COMPRESSION="xz"
COMPRESSION_OPTIONS=(-9e)
