# Teclado latinoamericano y estadounidense; Alt+Mayús alterna.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "latam,us"
        Option "XkbOptions" "grp:alt_shift_toggle"
EndSection
